name: Update
on:
  schedule:
    # - cron: "14 7 * * *"
  - cron: "*/5 * * * *"
  repository_dispatch:
    types: [updates]
  workflow_dispatch:
jobs:
  updates:
    name: Update Release Stats
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run ghr-collector (reviewdog/reviewdog)
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run ./cmd/ghr-collector/main.go -owner=reviewdog -repo=reviewdog
      - name: Set up Git.
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Commit
        run: |
          git commit -am "Update GitHub Release Stats"
      - name: Push
        run: |
          git push origin
