name: Update
on:
  schedule:
  - cron: "14 7 * * *"
  repository_dispatch:
    types: [updates]
  workflow_dispatch:
jobs:
  updates:
    name: Update Release Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ghr-collector (reviewdog/reviewdog)
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run ./cmd/ghr-collector/main.go -owner=reviewdog -repo=reviewdog
      - name: Generate SVG
        run: ./generate_svg.js
      - name: Set up Git.
        run: |
          git config user.name "GitHub Release Stats Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit
        run: |
          git add .
          git commit -m "Update GitHub Release Stats"
      - name: Push
        run: |
          git push origin
